name: Run commands when issues are labeled or comments added
on:
  issues:
    types: [labeled, opened]
  issue_comment:
    types: [created]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "wangyuan249/grafana-github-actions"
          path: ./actions
          ref: master
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
#          token: "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"
#          token: ${{secrets.GH_BOT_ACCESS_TOKEN}}
          configPath: issue-commands