name: Run commands when pull requests are opened/updated
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
#        with:
#          repository: "wangyuan249/grafana-github-actions"
#          path: ./actions
#          ref: master
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Commands
        uses: ./actions/commands
        with:
          token: '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'
#          token: ${{secrets.GH_BOT_ACCESS_TOKEN}}
          configPath: pr-commands